### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by dziban303** [elchininet/keep-texts-in-tabs#8]
Hi, I saw this in HACS and decided to try it. Unfortunately I can't get it to work. I've gone into the Edit Dashboard, then Raw Config Editor. 

The directions say to add the configuration to the very beginning of the code. Therefore I put it at line 1:

```yml
keep_texts_in_tabs:
  enabled: true
title: Home
views:
  - path: default_view
    title: Home
...
```

But that doesn't work: 
![image](https://github.com/elchininet/keep-texts-in-tabs/assets/7931765/7eab5006-5419-4e0c-917e-84c98aaf70c0)

I tried adding the code per dashboard page too,
```yml
title: Home
views:
  - keep_texts_in_tabs:
      enabled: true
    path: default_view    
    title: Home
...
  - keep_texts_in_tabs:
      enabled: true
    title: Weather
    path: weather
    icon: mdi:windsock
...
```
This also doesn't work, I just see the icons without the title text.

**Comment by elchininet** [comment]
Hi @dziban303,

Let‘s try to find out why it is now working on your side.
First thing to check is if the plugin is executing and there are no errors related to its execution.
Could you look at the console and check that the `console.info` is there?

<img width="212" alt="image" src="https://github.com/elchininet/keep-texts-in-tabs/assets/3728220/d99883cf-bbe7-4c34-80e0-5cfd8de755cb">

And also look in the console and in the logs for any suspicious error.

Regards

**Comment by elchininet** [comment]
By the way, try it only with your first configuration, your second configuration is not valid:

✅

```yaml
keep_texts_in_tabs:
  enabled: true
title: Home
views:
  - path: default_view
    title: Home
```

❌

```yaml
title: Home
views:
  - keep_texts_in_tabs:
      enabled: true
    path: default_view    
    title: Home
```
